### PR TITLE
Hypens replaced on monitor.record_gauge() function

### PR DESCRIPTION
**Pull request by FernandoGarzon**

### CODE REVIEW

**Comment by ericvaandering** [comment]
@dchristidis want to take a look at this? It does rename some metrics but I think that's necessary with the new record_gauge which is prometheus compatible. The current code does not work with the latest Rucio as stat is renamed to "name"

**Comment by ericvaandering** [comment]
No, but unfortunately the monitor method now ALSO has to be compatible with Prometheus names. That’s the way I understand it. But scraping will not work since the probes are ephemeral. The other option would be something that explicitly skips prometheus in the monitor methods.

In fact, longer term I’d like to see us get rid of the probes calling monitor at all and just use bare prometheus.

**Comment by FernandoGarzon** [comment]
Can we merge this one? Should I use PrometheusPusher here?

**Comment by voetberg** [comment]
Should we close this? The changes are overwritten by #147

**Comment by dchristidis** [comment]
Yes, I believe so. I’m not sure whether hyphens are problematic anymore. Should it prove to be the case, we can address it after the other PR is merged.

**Pull request closed without merging**
