### PR TITLE
Clean dead code #83

### PR DESCRIPTION
**Pull request by dchristidis**
Move unused probes to the attic directory. Move probes exclusively used by
ATLAS to the atlas directory. Remove tools directory.

### CODE REVIEW

**Review by ericvaandering — COMMENTED** [review]
I confirm nothing being moved from common is used by CMS

**Review by ericvaandering — APPROVED** [review]

**Comment by bari12** [comment]
For me this is fine too 👍

**Comment by cserf** [comment]
Looks good in general.
In atlas :
- `check_gridftp_space` should be moved to attic (replaced by `check_storage_space`)
- `check_rules` dead code
- `check_set_rse_space_limits`. URL pointing to AGIS :astonished: 
- `check_disabled_rses` is not really a probe but a script that can be used to identify deleted RSE in CRIC (BTW, still refers to AGIS)
- `check_stresstest_dids_requests_replicas_daily` : dead code
- `check_stresstest_dids_requests_replicas_hourly` : dead code
- `check_sync_rses_with_agis` : maybe rename to CRIC
- `graphite2nagios` pointing to `rucio-graphite-prod-02.cern.ch`. Probably dead code

In attic, you probably checked that the files there are not used. Just a few comments :
- `check_rses_distance` : I thought this one was still needed
- `check_metrix*` : For all these ones, better to check with @mlassnig 
- `check_scim` isn't it the one supposed to replace the `check_voms*` ?
- `check_oracle_partitions` was sometimes useful to detect problems with partitions not created. It happened a few times, and one just realized there's a problem when users complain. But maybe the DBA now have a way to monitor it

**Comment by dchristidis** [comment]
>     * `check_gridftp_space` should be moved to attic (replaced by `check_storage_space`)

Good catch. 

>     * `check_set_rse_space_limits`. URL pointing to AGIS astonished
>     * `check_disabled_rses` is not really a probe but a script that can be used to identify deleted RSE in CRIC (BTW, still refers to AGIS)
>     * `check_sync_rses_with_agis` : maybe rename to CRIC

Already fixed downstream. Will be fixed in a future pull request.

>     * `check_rules` dead code
>     * `check_stresstest_dids_requests_replicas_daily` : dead code
>     * `check_stresstest_dids_requests_replicas_hourly` : dead code

They are still running. If you’re confident that they aren’t doing anything useful, I would be glad to dispose them too.

>     * `graphite2nagios` pointing to `rucio-graphite-prod-02.cern.ch`. Probably dead code

Same as above.

>     * `check_rses_distance` : I thought this one was still needed

We’re not actively running it. Probably the cause of #16.

>     * `check_metrix*` : For all these ones, better to check with @mlassnig

They have a copy in our Puppet repository. They can be resurrected in the future, if necessary.

>     * `check_scim` isn't it the one supposed to replace the `check_voms*` ?

Yes, but in the future. For now, as it’s not actively running, the `attic` felt more appropriate.

>     * `check_oracle_partitions` was sometimes useful to detect problems with partitions not created. It happened a few times, and one just realized there's a problem when users complain. But maybe the DBA now have a way to monitor it

But it’s not actively running. It can remain in the `attic` in case we need to run it manually.

**Comment by ericvaandering** [comment]
I confirm we don't use any of the ones suggested by Cedric to remove.

**Comment by dchristidis** [comment]
Changed `check_gridftp_space` and `graphite2nagios`. The rest remained as they were.

**Pull request merged**
